version: "3"
services:
  db:
    image: kartoza/postgis:12.1
    hostname: db
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "docker"
    volumes:
      - pgdata:/var/lib/postgresql/data
  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    volumes:
      - ../:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: sh run_webapi.sh
volumes:
  pgdata:
